### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by rikirenz**

### CODE REVIEW

**Comment by rikirenz** [comment]
Hey @lnielsen. I was investigating this issue: https://github.com/inspirehep/inspire-next/issues/2453 that we have on inspire. So I was trying to move the ext file that @kaplun wrote in this PR: https://github.com/inspirehep/inspire-next/pull/2437 inside the project `invenio-xrootd`. But I discovered that tests do not pass on master:https://travis-ci.org/inveniosoftware/invenio-xrootd/builds/247112786?utm_source=github_status&utm_medium=notification. Do you have any ideas about how to solve this?

**Comment by kaplun** [comment]
> the ext file that @kaplun wrote

hehe actually @lnielsen wrote it and I merely copied into INSPIRE :smile:

**Comment by rikirenz** [comment]
@lnielsen ping :smile:

**Comment by lnielsen** [comment]
Travis doesn't output anything so can't say right now what the problem is and I'm on vacation for another week. Could probably be simple stuff like Sphinx or Pydocsstyle problems. See https://github.com/inveniosoftware/troubleshooting/issues

**Pull request closed without merging**
